version: '3.8'

services:
  db:
    container_name: postgres_search_by_itn
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  backend:
    container_name: backend_search_by_itn
    build:
      context: ./server
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:5000'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
  frontend:
    container_name: frontend_search_by_itn
    build:
      context: ./client
    depends_on:
      - db
      - backend
    restart: unless-stopped
    ports:
      - '80:80'